allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  vue-demi: true
overrides:
  brace-expansion@>=2.0.0 <2.1.5: ^2.1.5
  brace-expansion@>=2.0.0 <2.1.6: ^2.1.6
  brace-expansion@>=2.0.0 <2.1.7: ^2.1.7
  brace-expansion@>=4.0.0 <5.0.10: ^5.0.10
  brace-expansion@>=4.0.0 <5.0.11: ^5.0.11
  brace-expansion@>=4.0.0 <5.0.12: ^5.0.12
  devalue@<=5.9.2: ^5.9.3
  devalue@>=1.0.0 <=5.9.2: ^5.9.3
  devalue@>=5.1.0 <=5.9.2: ^5.9.3
  devalue@>=5.8.0 <=5.9.2: ^5.9.3
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  serialize-javascript@>=7.1.1 <7.1.2: ^7.1.2
